# Generated by Django 4.1 on 2022-10-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_alter_address_id_alter_counter_id_alter_room_id_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='units',
            field=models.ManyToManyField(to='units.unit'),
        ),
    ]
