# Generated by Django 4.1 on 2022-10-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='integration_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='código de integração'),
        ),
    ]
