# Generated by Django 4.1 on 2022-10-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_address_id_alter_counter_id_alter_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='is_constrained_by_queue',
            field=models.BooleanField(default=True, help_text='Chama somente as senhas de suas respectivas filas.', verbose_name='limitado as filas'),
        ),
    ]
