# Generated by Django 4.1 on 2022-10-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_counter_is_constrained_by_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='busy',
            field=models.BooleanField(default=False, verbose_name='ocupado'),
        ),
    ]
