# Generated by Django 4.1 on 2022-10-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0003_queue'),
        ('units', '0005_alter_room_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='priorities',
            field=models.ManyToManyField(to='attendant.priority', verbose_name='prioridades'),
        ),
    ]
