# Generated by Django 4.1 on 2022-10-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_counter_priorities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='descrição'),
        ),
    ]
