# Generated by Django 4.1 on 2022-08-20 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DELETED', 'Removido'), ('DEACTIVATED', 'Desativado'), ('ACTIVATED', 'Ativado')], default='ACTIVATED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(max_length=150, verbose_name='descrição')),
                ('abbreviation', models.CharField(max_length=20, verbose_name='sigla')),
                ('personalized_service', models.BooleanField(default=True, verbose_name='atendimento personalizado')),
                ('importance', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='peso')),
                ('units', models.ManyToManyField(to='units.unit')),
            ],
            options={
                'verbose_name': 'prioridade',
            },
        ),
    ]
