# Generated by Django 4.1 on 2022-10-08 14:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_address_id_alter_counter_id_alter_room_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='priority',
            name='units',
            field=models.ManyToManyField(to='units.unit', verbose_name='unidades'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DELETED', 'Removido'), ('DEACTIVATED', 'Desativado'), ('ACTIVATED', 'Ativado')], default='ACTIVATED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número')),
                ('is_reactivated', models.BooleanField(default=False, verbose_name='reativada')),
                ('times_called', models.IntegerField(default=0, verbose_name='vezes chamadas')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendant.priority', verbose_name='prioridade')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.unit', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'senha',
            },
        ),
        migrations.CreateModel(
            name='Forwarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DELETED', 'Removido'), ('DEACTIVATED', 'Desativado'), ('ACTIVATED', 'Ativado')], default='ACTIVATED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='data de finalização')),
                ('start_at', models.DateTimeField(null=True, verbose_name='data de atendimento')),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='atendente')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.counter', verbose_name='guichê')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.room', verbose_name='ambiente')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendant.ticket', verbose_name='senha')),
            ],
            options={
                'verbose_name': 'encaminhamento',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DELETED', 'Removido'), ('DEACTIVATED', 'Desativado'), ('ACTIVATED', 'Ativado')], default='ACTIVATED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='data de finalização')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='units.counter', verbose_name='guichê')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendant.ticket', verbose_name='senha')),
            ],
            options={
                'verbose_name': 'chamada',
            },
        ),
    ]
